version: '3.8'

services:
  app:
    container_name: app
    restart: on-failure
    depends_on:
      - postgres
    image: node:18-alpine
    ports:
      - "3000:3000"
      - "5555:5555" # prisma studio
    working_dir: /app
    volumes:
      - .:/app/
      - /app/node_modules/
    command: sh -c "yarn && yarn prisma migrate dev && yarn prisma generate && yarn dev"
    environment:
      NODE_ENV: development
      APP_PORT: 3000
      DATABASE_URL: postgresql://user:password@postgres:5432/db?schema=public
      JWT_ISSUER: mytube
      JWT_SECRET: secret

  postgres:
    container_name: postgres
    restart: on-failure
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

volumes:
  postgres-data:
